const API_PATH = {
  apiUserLogin: "/api/login",
  apiAddUser: "/api/user/addUser",
  apiGetUser: "/api/user/getUserDetails/",
  apiGetUserList: "/api/user/getUserList/",
  apiAddTask: "/api/task/addTask",
  apiProjectAdd: "/api/project/addProject",
  apiGetTaskList: "/api/task/getTaskList",
  apiGetTaskDetails: "/api/task/getTaskDetails/",
  apiUpdateTask: "/api/task/UpdateTask",
  apiCommonComponent: "/api/common/getCommonComponent",
  apiGetProject: "/api/project/getProjectList",
  apiApplyNewHoliday: "/api/holiday/applyNewHoliday",
  apiHolidayList: "/api/holiday/getHolidayList",
  apiChat: "/api/chat",
  getChatsList: "/api/chat/getChatsList",
  searchUser: "/api/chat/searchUser/",
  getMessage: "/api/chat/getMessage/",
  apiAssignProject: "/api/project/assignProject",
  getProjectDetails: "/api/project/getProjectDetails",
  getProjectTaskList: "/api/task/getProjectTaskList",
  apiCreateTeam: "/api/team/createTeam",
  apiGetTeamList: "/api/team/getTeamList",
  me: "/api/user/me",
  getRoleList: "/api/permission/getAllRoleList",
  getRoleDetails: "/api/permission/getRoleDetails",
  createRole: "/api/permission/createRole",
  getAllModules: "/api/module/getAllModules",
};

export default API_PATH;
